# Use OpenJDK 17
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /app

# Copy Maven/Gradle build files
COPY pom.xml ./
COPY src ./src

# Build the app
RUN ./mvnw clean && ./mvnw package -DskipTests

# Expose port
EXPOSE 8080

# Run the jar
CMD ["java", "-jar", "target/01blog-0.0.1-SNAPSHOT.jar"]
